name: Slackbot on release

on:
  release:
    types: [published]  # Triggers when a pre-release is changed to a full release

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    
    steps:
      - name: Notify Slack on Releases
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "ðŸš€ New Lighthouse published: *${{ github.event.release.tag_name }}*\n\n${{ github.event.release.body }}"
